{
  # these validations are related to SRS Travels
  validateOdometerInFuel		      : true,
  validateOdometerInIssues        : true,
  validateOdometerInTripSheet     : true,
  validateOdometerInWorkOrder     : true,
  validateMinOdometerInWorkOrder  : true,
  validateMinOdometerInIssues     : true,
  validateMinOdometerInFuel       : true,
  validateMinOdometerInTripSheet  : true,
  #these validations are related to Durgamba 
  validateOdometerInTripDailySheet : false,
  allowedPerDiffInOdometer         : 10,
  maxBackDateEntryAloowed          : 15,
  asignAnySizeTyre                 : false,
  showDriverMonthlySalary		   : false,
  importDataToTally                : false,
  showVehicleColor                 : true,
  showClassOfVehicle               : true,
  showVehicleBody                  : true,
  showRoute                        : true,
  showACType                       : true,
  showCylinder                     : true,
  showCubicCapacity                : true,
  showPower                        : true,
  showWheelBase                    : true,
  showSeatCapacity                 : true,
  showVehicleLocation              : true,
  fuelTankText                     : "Fuel Tank Capacity",
  showMobileNumber                 : false,
  validateChasisNo	               : true,
  validateVGroup	               : true,
  allowVehicleAgentPayment         : true,
  addVehicleDetailsAjax            : true,
  validateEngineNo                 : true,
  validateVehicleType              : true,   
  validateVehicleStatus            : true,
  validateVehicleFuelType          : true,
  validateVehicleOdometer          : true,
  validateVehicleExpectedOdometer  : true,
  validateVehicleExpectedMileage   : true,
  showBusIdDetails                 : false,
  showDriverNameInAddOwnerShip     : false,
  showDriverPhoneNoInAddOwnerShip  : false,
  showVehicleOwnerSrNo             : false, 
  vehicleMonthlyEMIPayment         : false,
  asignAnyCapacityBattery          : false,
  vehicleExcludingSurrenderAndInactive : false,    
  inactiveVehicleInRR                  : false,   
  branchWiseVehicleInspection      : false,
  selectServiceProgramOnModal      : true,
  validateVehicleModal             : false ,
  showTotalVehicleCount            : false,
  vehicleModelTyreLayout           : false,
  assignDiffTyreModel              : false,
  validateTyreSize                 : false,
  accidentClaim                    : false,
  accidentSpotservay               : false,
  accidentDocValidate              : false,
  accidentAdditionalFields         : false,
  addVehicleStatusRemark           : false,
  showOnlyCompanyVehicleType       : false,
  showVehicleBodyMaker 			   : false,
  vehicleTyreMountCostInPLReport   : false, 
  allowMaximumOdometer             : "5000",
  showTollIdFeild				   : false,
  showSubCompanyDropdown           : false,
  allowVehicleNameInLedger         : false
 }
  
