{
showBreakdownSelection			   : false,
showIssuesLabelOption			   : true,
customerIssue                      : false,
showBreakDownDetails               : false,
issuesAjax                         : true,
showCategoryOption				   : false,
showRouteOption					   : false,
setDefaultServerDateAndTime        : false,
allowedMobNotification             : true,
showDateWiseOverdue                : false,
hideLowStatus                      : false,
hideHighStatus                     : false,
resolveIssueViaOnlyWODSE           : false,
showGroupInIssueSummary            : false,
additionalInfoInIssueView     : false,
showVehicleTypeAndMaker       : true,
showVehicleGroup              : false,
showLocation                  : false,

multipleIssues                : false,
closureWithRemark             : false,
issueAnalysis                 : false,
issueAsignId                  : "",
tyreAssginFromIssue           : false,
tyreCategoryId                : 612,
createIssueFromHealth         : false,
validateOdometer              : false
} 