package org.fleetopgroup.persistence.service;

import java.util.Date;

import org.fleetopgroup.constant.SequenceTypeContant;
import org.fleetopgroup.persistence.dao.BatteryInvoiceSequenceRepository;
import org.fleetopgroup.persistence.dao.BusBookingSequenceRepository;
import org.fleetopgroup.persistence.dao.CashBookSequenceRepository;
import org.fleetopgroup.persistence.dao.CashBookVoucherSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.ClothInvoiceSequenceRepository;
import org.fleetopgroup.persistence.dao.DriverSalaryAdvanceSequenceRepository;
import org.fleetopgroup.persistence.dao.FuelInvoiceSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.FuelSequenceRepository;
import org.fleetopgroup.persistence.dao.InventoryRequisitionSequenceRepository;
import org.fleetopgroup.persistence.dao.InventorySequenceRepository;
import org.fleetopgroup.persistence.dao.InventoryTyreSequenceRepository;
import org.fleetopgroup.persistence.dao.IssuesSequenceRepository;
import org.fleetopgroup.persistence.dao.LorryHirePaymentSequenceRepository;
import org.fleetopgroup.persistence.dao.PartInvoiceSequenceRepository;
import org.fleetopgroup.persistence.dao.PurchaseOrderSequenceRepository;
import org.fleetopgroup.persistence.dao.RefreshmentSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.RenewalApprovalSequenceRepository;
import org.fleetopgroup.persistence.dao.RenewalReminderSequenceRepository;
import org.fleetopgroup.persistence.dao.SentLaundryInvoiceSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.ServiceEntriesSequenceRepository;
import org.fleetopgroup.persistence.dao.ServiceReminderSequenceRepository;
import org.fleetopgroup.persistence.dao.TripDailyAllGroupDaySequenceRepository;
import org.fleetopgroup.persistence.dao.TripDailyGroupCollectionSequenceRepository;
import org.fleetopgroup.persistence.dao.TripDailySheetSequenceRepository;
import org.fleetopgroup.persistence.dao.TripRouteSequenceRepository;
import org.fleetopgroup.persistence.dao.TripSheetCollectionSequenceRepository;
import org.fleetopgroup.persistence.dao.TripsheetSequenceRepository;
import org.fleetopgroup.persistence.dao.UreaEntriesSequenceRepository;
import org.fleetopgroup.persistence.dao.UreaInvoiceSequenceRepository;
import org.fleetopgroup.persistence.dao.VehicleAccidentSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.VendorApprovalSequenceRepository;
import org.fleetopgroup.persistence.dao.VendorLorryHireSequenceCounterRepository;
import org.fleetopgroup.persistence.dao.VendorSequenceRepository;
import org.fleetopgroup.persistence.dao.WorkOrderSequenceRepository;
import org.fleetopgroup.persistence.model.BatteryInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.BusBookingSequenceCounter;
import org.fleetopgroup.persistence.model.CashBookName;
import org.fleetopgroup.persistence.model.CashBookSequenceCounter;
import org.fleetopgroup.persistence.model.CashBookVoucherSequenceCounter;
import org.fleetopgroup.persistence.model.ClothInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.DriverSalaryAdvanceSequenceCounter;
import org.fleetopgroup.persistence.model.FuelInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.FuelSequenceCounter;
import org.fleetopgroup.persistence.model.InventoryRequisitionSequenceCounter;
import org.fleetopgroup.persistence.model.InventorySequenceCounter;
import org.fleetopgroup.persistence.model.InventoryTyreSequenceCounter;
import org.fleetopgroup.persistence.model.IssuesSequenceCounter;
import org.fleetopgroup.persistence.model.LorryHirePaymentSequenceCounter;
import org.fleetopgroup.persistence.model.PartInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.PurchaseOrdersSequeceCounter;
import org.fleetopgroup.persistence.model.RefreshmentSequenceCounter;
import org.fleetopgroup.persistence.model.RenewalApprovalSequenceCounter;
import org.fleetopgroup.persistence.model.RenewalReminderSequenceCounter;
import org.fleetopgroup.persistence.model.SentLaundryInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.ServiceEntriesSequenceCounter;
import org.fleetopgroup.persistence.model.ServiceReminderSequenceCounter;
import org.fleetopgroup.persistence.model.TripCollectionSequenceCounter;
import org.fleetopgroup.persistence.model.TripDailyAllGroupDaySequenceCounter;
import org.fleetopgroup.persistence.model.TripDailyGroupCollectionSequenceCounter;
import org.fleetopgroup.persistence.model.TripDailySheetSequenceCounter;
import org.fleetopgroup.persistence.model.TripRouteSequenceCounter;
import org.fleetopgroup.persistence.model.TripSheetSequenceCounter;
import org.fleetopgroup.persistence.model.UreaEntriesSequenceCounter;
import org.fleetopgroup.persistence.model.UreaInvoiceSequenceCounter;
import org.fleetopgroup.persistence.model.VehicleAccidentSequenceCounter;
import org.fleetopgroup.persistence.model.VendorApprovalSequenceCounter;
import org.fleetopgroup.persistence.model.VendorLorryHireSequenceCounter;
import org.fleetopgroup.persistence.model.VendorSequenceCounter;
import org.fleetopgroup.persistence.model.WorkOrderSequenceCounter;
import org.fleetopgroup.persistence.serviceImpl.ICashBookNameService;
import org.fleetopgroup.persistence.serviceImpl.ISequenceService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class SequenceService implements ISequenceService {
	
	@Autowired	private TripRouteSequenceRepository					tripRouteSequenceRepository;
	@Autowired	private DriverSalaryAdvanceSequenceRepository		driverSalaryAdvanceSequenceRepository;
	@Autowired	private	RenewalReminderSequenceRepository			renewalReminderSequenceRepository;
	@Autowired	private	RenewalApprovalSequenceRepository			renewalApprovalSequenceRepository;
	@Autowired	private ServiceReminderSequenceRepository			serviceReminderSequenceRepository;
	@Autowired	private ServiceEntriesSequenceRepository			serviceEntriesSequenceRepository;
	@Autowired	private FuelSequenceRepository						fuelSequenceRepository;
	@Autowired	private IssuesSequenceRepository					issuesSequenceRepository;
	@Autowired	private VendorSequenceRepository					vendorSequenceRepository;
	@Autowired	private VendorApprovalSequenceRepository			vendorApprovalSequenceRepository;
	@Autowired	private InventorySequenceRepository					inventorySequenceRepository;
	@Autowired	private InventoryTyreSequenceRepository				inventoryTyreSequenceRepository;
	@Autowired	private TripsheetSequenceRepository					tripsheetSequenceRepository;
	@Autowired	private TripSheetCollectionSequenceRepository		tripSheetCollectionSequenceRepository;
	@Autowired	private TripDailyAllGroupDaySequenceRepository		tripDailyAllGroupDaySequenceRepository;
	@Autowired	private TripDailySheetSequenceRepository			tripDailySheetSequenceRepository;
	@Autowired	private TripDailyGroupCollectionSequenceRepository	tripDailyGroupCollectionSequenceRepository;
	@Autowired	private PurchaseOrderSequenceRepository				purchaseOrderSequenceRepository;
	@Autowired	private WorkOrderSequenceRepository					workOrderSequenceRepository;
	@Autowired	private CashBookSequenceRepository					cashBookSequenceRepository;
	@Autowired	private InventoryRequisitionSequenceRepository		inventoryRequisitionSequenceRepository;
	@Autowired	private ICashBookNameService						cashBookNameService;
	@Autowired	private BatteryInvoiceSequenceRepository			sequenceRepository;
	@Autowired	private PartInvoiceSequenceRepository				partInvoiceSequenceRepository;
	@Autowired	private ClothInvoiceSequenceRepository				clothInvoiceSequenceRepository;
	@Autowired	private SentLaundryInvoiceSequenceCounterRepository	sentLaundryInvoicedao;
	@Autowired	private LorryHirePaymentSequenceRepository			lorryHirePaymentSequenceRepository;
	@Autowired	private VendorLorryHireSequenceCounterRepository	vendorLorryHireSequenceCounterRepository;
	@Autowired	private UreaInvoiceSequenceRepository				ureaInvoiceSequenceRepository;
	@Autowired	private UreaEntriesSequenceRepository				ureaEntriesSequenceRepository;
	@Autowired	private RefreshmentSequenceCounterRepository		refreshmentSequenceCounterRepository;
	@Autowired	private BusBookingSequenceRepository				busBookingSequenceRepository;
	@Autowired	private CashBookVoucherSequenceCounterRepository	cashBookVoucherRepository;
	@Autowired	private FuelInvoiceSequenceCounterRepository		fuelInvoiceSequenceCounterRepository;
	@Autowired	private VehicleAccidentSequenceCounterRepository	vehicleAccidentSequenceCounterRepository;
	
	@Override
	public void insertSequenceTableEntries(Integer companyId) throws Exception {
		
		tripRouteSequenceRepository.save(new TripRouteSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		driverSalaryAdvanceSequenceRepository.save(new DriverSalaryAdvanceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		renewalReminderSequenceRepository.save(new RenewalReminderSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		renewalApprovalSequenceRepository.save(new RenewalApprovalSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		serviceReminderSequenceRepository.save(new ServiceReminderSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		serviceEntriesSequenceRepository.save(new ServiceEntriesSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		fuelSequenceRepository.save(new FuelSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		issuesSequenceRepository.save(new IssuesSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		vendorSequenceRepository.save(new VendorSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		vendorApprovalSequenceRepository.save(new VendorApprovalSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		inventorySequenceRepository.save(new InventorySequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER, SequenceTypeContant.SEQUENCE_TYPE_PART_INVENTORY));
		inventorySequenceRepository.save(new InventorySequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER, SequenceTypeContant.SEQUENCE_TYPE_TYRE_INVENTORY));
		inventorySequenceRepository.save(new InventorySequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER, SequenceTypeContant.SEQUENCE_TYPE_INVENTORY_TYRE_RETREAD));
		inventoryTyreSequenceRepository.save(new InventoryTyreSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		tripsheetSequenceRepository.save(new TripSheetSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		tripSheetCollectionSequenceRepository.save(new TripCollectionSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		tripDailyAllGroupDaySequenceRepository.save(new TripDailyAllGroupDaySequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		tripDailySheetSequenceRepository.save(new TripDailySheetSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		tripDailyGroupCollectionSequenceRepository.save(new TripDailyGroupCollectionSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		purchaseOrderSequenceRepository.save(new PurchaseOrdersSequeceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		workOrderSequenceRepository.save(new WorkOrderSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		cashBookSequenceRepository.save(new CashBookSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		inventoryRequisitionSequenceRepository.save(new InventoryRequisitionSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		CashBookName	bookName = new CashBookName("MAIN-CASH-BOOK", "THIS IS MAIN CASH BOOK",(long) 0, new Date(), companyId, 0);
		cashBookNameService.add_CashBookName(bookName);
		cashBookVoucherRepository.save(new CashBookVoucherSequenceCounter(bookName.getNAMEID(),(long) 1, companyId));
		sequenceRepository.save(new BatteryInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		partInvoiceSequenceRepository.save(new PartInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER, (short) 1));
		clothInvoiceSequenceRepository.save(new ClothInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		sentLaundryInvoicedao.save(new SentLaundryInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		lorryHirePaymentSequenceRepository.save(new LorryHirePaymentSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		vendorLorryHireSequenceCounterRepository.save(new VendorLorryHireSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		ureaInvoiceSequenceRepository.save(new UreaInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		ureaEntriesSequenceRepository.save(new UreaEntriesSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		refreshmentSequenceCounterRepository.save(new RefreshmentSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		busBookingSequenceRepository.save(new BusBookingSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		fuelInvoiceSequenceCounterRepository.save(new FuelInvoiceSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
		vehicleAccidentSequenceCounterRepository.save(new VehicleAccidentSequenceCounter(companyId, ISequenceService.STARTING_SEQUENCE_NUMBER));
	}
}
