{validateServiceReminder              : false,
driver2	                              : true,
conductor                             : true,
cleaner                               : true,
showTripSheetOptions	              : false,
showExtraReceived                     : false,
showSubroute                          : false,
hideClosedTripSheet                   : false,
showAdvanceDriver                     : false,
tripIncome                            : false,
showClosingKMOnRoute                  : true,
showLoadType                          : false,
showCombineTripDetails                : false,
allowBackDateEntry                    : false,
noOfDaysForBackDate                   : 0,
addLhpvAfterTripSheet                 : false,
allowMultipleExpensesOfSameType       : false,
allowShortCutInTripSheet              : true,
showTimeDuringCloseTripsheet          : true,
showPODdetails                        : false,
allowIVLoadingSheetEntry              : false,
loadingSheetChargesType               : 1,
loadingSheetSyncLink                  : "",
dontAddIVCargoIncomeToTripSheet		  : false,
includeOnlyToPayLrs                   : false,
showExpenseInPrintBeforeClosing       : true,
allowToEditVehicleInTripSheet         : false,
allowToEditTripSheetCloseDate		  : false,
loadingSheetIncomeId                  : 2203,
allowTicketIncomeApiIntegeration      : false,
CompanyID                             : 0,
urlForTcktIncmApi                     : "",
tcktIncmName                          : "Bus Ticket Income Api",
ticketIncomeId                        : 2204,
showAlwaysDispatchTime                : true,
showCreditAndVendorAtExpense          : false,
allowMultipleIncomeOfSameType         : false,
dispatchTripPrint                     : false,  
showTripsheetNetIncomeAmount          : false,
driverPenaltyDetails                  : false,
hideGroupService                      : false,
allowedPerDiffInOdometer              : 10,
tripOpenCloseFuelRequired             : false,
allowToCloseTripSheetBeforeDate       : false,
validateClosingOdometerOnRoute        : true,
showTotalKmpl                         : true,
driverHaltBataFinalAmount             : false,
TallyCompanyMasterInDriverHalt        : false,
showDriverBalance                     : false,
allowITSGatewayBusIncome              : false,
verifyCallForITSGateway               : "",
allowITSGatewayDriverDetails          : false,
urlForDriverDetailsItsGatewayApi      : "",
allowedKMForExtendedTrip              : 2000,
includeServiceEntryAsExpense          : false,
includeRenewalAsExpense               : false, 
allowTallyIntegration                 : false,
showTripsheetDueAmount                : false, 
showTripBookngRef                     : false,
tripPrintFixedSize                    : false, 
showRoutePoint                        : true,
driverBalanceWithNarration            : false,
payToDriverText                       : "To Be Paid To Driver",
payToOfficeText                       : "Have To Take From Driver",
removeAdvanceFromDriverBalance        : false,
validateOdometerInTripSheet           : true,
allTableRequiredBeforeClose           : true,
meterNotWorkingDontValidate           : true,
updateClosingKm                       : false,
updateOpeningKm                       : false,
deleteTripSheetAfterClose             : false,
superUserDelete                       : true,
addTripExpenseDocument                : false,
downloadTripExpenseDocument           : false,
addMultipleTripExpenseDocument        : false,
downloadMultipleTripExpenseDocument   : false,
preparedByAndAuthorizedBy             : false,
showToPayPaidTotalOfLS                : false,
lhpvAsExpense                         : false,
manualVsGpsKmDifference				  : 3.0,
showTypePlaceRefInIncomeExpense		  : true,
reverseDriverBalance                  : false,
showDriverExcludeAtIncome             : false,
substractTimeFromDate                 : false,
noOfHourToSubstract                   : 0,
roundFigureAmount                     : false,
showTripCommentInPrint				  : true,
esiPercetage                          : "0.75",
pfPercentage                          : "12",
showPFAmount                          : false,
dailyAllowanceIds                     : "0,0",
vehicleHeaderOnPrint                  : false,
routeHeaderOnPrint                    : false,
allowBitlaApiIncome                   : false,
bitlaApiKeyUrl                        : "",
bitlaApiUserName                      : "",
bitlaApiPassword                      : "",
updateOpeningClosingOnBackEntry       : false,
bitlaApiTransactionDetailsUrl         : "",
removeAdvanceAfterClose               : false,
addTripDocument                       : false,
dateRangeInDateWiseExpenseReport      : false,
showDriverFullName                    : false,
showDiffAvgCost                       : false,
validateTripCloseTimeAsCurrentTime    : true,
driverInputFieldInDateWiseExpenseReport     : false,
showTripdateWithTime                    : false,
allowAutoIncomeOnTripClose              : true,
allowAccountCloseWithoutIncome          : true,
allowAutoLSOnTripClose                : true,          
noOfDaysForBackDateForAdmin           : 60,
driverFuelMileageAlert                : false,
groupValidationinBranchWiseAdvanceReport : false, 
checkPointParameterDocumnet           : false,
allowMantisDispatchIncome              : false,
mantisDispatchIncomeUrl               : "",
mantisDipatchIncomeAPIKey            : "",
allowCloseWithNoGPSandFastag         : false,
showVehicleGroupWiseCompany          : false,
showGPSodoInOpeningKm                : false,
 validateDirectOdometerUpdate        : true,
 doNotConsiderCrossLR				 : false,
hideAdvanceAndExpenseAddIfAccClose		: false,
transferDriverBalanceToNextTrip			: false,
disableAdvanceDuringDispatch			: false,
payToOfficeOnlyWhileClosingTrip			: false,
saveDriverLedgerDetails				: false,
addMoreButtonInTripIncomeExpense	: true,
showPaymentTypeInIncomeExpense		: false,
showLastTripMileageOnCloseTrip			: false,
lorryHireIncomeId						: 2413,
showExpensePrint 					: false,
allowTallyPushButtonOnClose			: false,
tripsheetColorPrint                 : false,
exchangeTypeWithAmountRefWithAmount : false,
exchangeTypeWithAmountRefWithAmountPrint : false,
getDriverBalance						: false,
customeTripsheetPrint				: false,
hideVoucherDate							: false,
hideTallyCompany						: false,
directAccountClose						: false,
showVehicleSearchAfterACCClose			: false,
showLsSourceAndDestination				: false,
showDefaultTimeAndDate                  : true,
addInDriverbalanceAfterTripClose 		: false,
IncCashExpenseInDriBal					: false,
includeOnlineExpenseInDriverExpense		: false,
showDriverBalConfigInTripsheetPrint		: false,
showLsDestination		         	    : false,
validateDriverOnTripsheet				: false,
changedDriverFieldName					: false,
showWithOrWithoutBill					: false,
changedDriverBalance					: false,
changedTripBalance					    : false,
getBIncomeEIncome					    : false,
showDriverBalanceBifurcation			: false,
showbilltypeDropdown                  	: false,
showDueIncomeType					    : false,
validateBillTypeIncome				    : false,
pushTripsheetStatusToIvCargo            : false,
pushTripsheetStatusToIvCargoApiLink     : "",
showTimeDuringAddTripsheet              : true,
addtripIncomeAsBIncome					: false,
validateTripRoutePoint                  : false,
showFuelKmplOnFullFuelEntry				: false,
diffFuleUsageKmlogic					: false,
newLogicForTripSheetDriverBalance       : false
}
