{ 
showCashBookStatus                : true,
showLinkRefLink                   : false,
showGstNoCol                      : false,
showApprovalButton                : true,
AllowEditAfterClose               : false,
isAutoVoucherNumber               : false,
linkingNotNeededToGroup           : "0",
closeDatePayment                  : 20,
missingCashbookBackDateStart      : 1,
missingCashbookBackDateEnd        : 153,
oldCashbookBackDateStart          : 1,
oldCashbookBackDateEnd            : 15,
allowZeroAmountCashBook			  : false,
addTripIncomeInCashBook		      : false,
checkAuthorityForCashBook         : false,
addDueExpenseInCashBook			  : false,
viewCashReference				  : false,
showCashBookReference			  : false
}