{
saveRenewalWithoutFile                : false,
optionalInformation                   : true,
showAuthorizationState                : false,
receiptnumbershow                     : false,
modeofaaymentshow                     : false,
cashtransactionshow                   : false,
paidDateshow                          : true,
paidbyshow                            : false,
validateDuplicateRefnumber            : true,
alwaysApprovedRenewal                 : true,
showVendorCol                         : false,
showDueThreshold					  : true,
showDueThresholdPeriod				  : true,
showRRNotification                    : false,
tallyIntegrationRequired              : false,
createApproval                        : false,
defaultPaidDate                       : false,
rrDueRepostShoeVehicleStatus : false ,
ignoreRenewal                         : false,
dateValidation                        : true ,
hideRenewalTypes                      : false,
stopIvCargoCashBookEntries			  : false    
}