{
tallyIntegrationRequired     : false,
showBuyerGstNumber           : false,
editPartDetails              : false,
eachTotalCost                : true,
totalGstCost                 : true,
totalDiscountCost            : true,
finalTotalCost               : true,
finalBalanceCost             : true,
editVendorInPO               : false,
editShipToLocation           : false,
makeApproval                 : false,
defaultShipVia               : false,
showQuoteNumber              : true,
ManualIndentNo               : true,
WorkOrderNo                  : true,
previousPOpartRate           : false,
locationWisePartCount        : false,
showSustitutePartCount       : false,
KHTCprintConfig              : false,
showShipvia                  : true,
showShipAddress              : true,
showNotes                    : true,
customPuchaseOrderprint 	 : 'showPurchaseOrderPrintForAadinath',
showCustomPurchaseOrderPrint : false,
showPrint                    : true,
allowToReceivePartial		 : false,
poApprovalRequired			 : false,
requisitionApproved 		 : false,
showSaveRemarkButton	     : false,
editInvoiceNoLength			 : false
}