{showVehicleCol				: true,
showVehicleDepotCol			: true,
showFuelTypeCol				: true,
showReferenceCol			: true,
showPersonalExpenceCheck	: true,
showFuelDocumentSelection	: true,
showFuelCommentField		: true,
referenceName               : false,
showDriver2                 : false,  
showCleaner                 : false,
showRoute                   : false,
resetAllFuelEntries         : true,
resetFuelVehicle            : false,
resetFuelDate               : false,
resetFuelOdometer           : false,
resetFuelType               : false,
resetFuelVendor             : false,
resetFuelLiter              : false,     
resetFuelPrice              : false,     
resetFuelReference          : false,     
resetFuelDriver             : false,     
resetFuelDriverTwo          : false,     
resetFuelCleaner            : false,     
resetFuelRoute              : false,     
resetFuelImage              : false,
resetFuelComment            : false,
selectAutoCredit            : false,
AllowWSFuelEntry            : true,
lastFuelAsOpen              : true,
showTripSheetDropDown       : true,
noOfDaysToShowTripSheet     : 10 ,
validateDriver1             : false,
showVehicleNumCol		  	: true,
showFuelReferenceNumCol	    : false,
showDriverNameCol			: false,
tallyImportRequired           : false,
validateTripSheetNumber       : false,
noOfDaysForBackDate           : 15,
validateReference             : true,
validateUniqueReference       : false,
allowToEditFuelRef            : false,
considerFirstEntry            : false,
showMarkAsVoidAutoSelected    : false,
doNotValidateBackDateEntries  : false,
bindMinMaxOdometerOnTripSheet : false,
allowManualOdometerEntry      : false,
addFuelDocument               : false,
allowToAddFuelAmount          : false,
roundFigureAmount             : false,
allowFuelEntryTime            : true,
setDefaultDriverForVehicle    : false,
showKmplOnPartialEntry        : false,
showDriverFullNameInFuel      : false,
showDocColumnInDailyConsReport : false,
blockGalleryImageSelection     : false,
setFuelEntryDefaultDateAndTime : false,
getStockFromInventory         : false,
showCurrnetDateAndTime        : false,
allowCustomExcelDownload      : false,
showGPSKMPLInVFuelReport      : false,
showAmountPerLiterCol         : false,
paidByOptionInAddFuleEntry 	  : false,
showBranchToUserWiseReport	  : false,
maxFuelPrice				  : 125,
maxFuelLiters				  : 1000,
fuleEntryPaymentOptions		  : false,
showPaymentMode				  : false,
showVehicleNoInFuelReport	  : false,
maxOdometerAsTripCloseKM      : false
}