select * from VehicleTyreModelType  order by TYRE_MODEL ASC;

#update VehicleTyreModelType set markForDelete = 1 where COMPANY_ID <> 0;

#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (87,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','APOLLO TYRES','APOLLO TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (88,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','BIRLA TYRES','BIRLA TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (89,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','BRIDGESTONE','BRIDGESTONE',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (90,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','CAVENDISH','CAVENDISH',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (91,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','CEAT','CEAT',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (92,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','CHALENGER','CHALENGER',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (93,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','CHINA TYRES','CHINA TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (94,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','GOODRICH ST 270','GOODRICH ST 270',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (95,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','JK CHALLENGER','JK CHALLENGER',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (96,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','JK INDIA RADIALS','JK INDIA RADIALS',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (97,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','JK TYRES','JK TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (98,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','MRF','MRF',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (99,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','MICHELIN','MICHELIN',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (100,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','PIRELLI TYRE','PIRELLI TYRE',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (101,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','TEASER','TEASER',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (102,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','TRIANGLE TYRES','TRIANGLE TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (103,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','TVS TYRES','TVS TYRES',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (104,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','VIKRANTH','VIKRANTH',0,0);
#insert into VehicleTyreModelType (TYRE_MT_ID,COMPANY_ID,CREATEDBYID, CREATED_DATE, LASTMODIFIEDBYID, LASTMODIFIED_DATE, TYRE_MODEL, TYRE_MODEL_DESCRITION, markForDelete, isOwnTyreModel) values (105,0, 0, '2018-08-31 14:09:48', 0, '2018-08-31 14:09:48','YATAI CHINA','YATAI CHINA',0,0);

SELECT CONCAT('#UPDATE ',TABLE_NAME,' SET ',COLUMN_NAME,' = 19 WHERE ',COLUMN_NAME,' = 10; ') 
FROM INFORMATION_SCHEMA.COLUMNS
    WHERE COLUMN_NAME like '%TYRE_MANUFACTURER_ID%'
        AND TABLE_SCHEMA='fleetopgroup';
        
        
        
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 87 WHERE TYRE_MT_ID IN (87,77,66,61,55,5);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 88 WHERE TYRE_MT_ID IN (71,54,62); 
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 89 WHERE TYRE_MT_ID IN (2,80,60);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 90 WHERE TYRE_MT_ID IN (81);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 91 WHERE TYRE_MT_ID IN (76,64,58);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 92 WHERE TYRE_MT_ID IN (65);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 93 WHERE TYRE_MT_ID IN (74);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 94 WHERE TYRE_MT_ID IN (67);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 95 WHERE TYRE_MT_ID IN (68);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 96 WHERE TYRE_MT_ID IN (1);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 97 WHERE TYRE_MT_ID IN (51,69);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 98 WHERE TYRE_MT_ID IN (73,63,57);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 99 WHERE TYRE_MT_ID IN (59,70,84);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 100 WHERE TYRE_MT_ID IN (75);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 101 WHERE TYRE_MT_ID IN (83);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 102 WHERE TYRE_MT_ID IN (6,53);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 103 WHERE TYRE_MT_ID IN (78);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 104 WHERE TYRE_MT_ID IN (74);
    #UPDATE VehicleTyreModelSubType SET TYRE_MT_ID = 105 WHERE TYRE_MT_ID IN (52);



    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 87 WHERE TYRE_MANUFACTURER_ID IN (87,77,66,61,55,5);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 88 WHERE TYRE_MANUFACTURER_ID IN (71,54,62); 
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 89 WHERE TYRE_MANUFACTURER_ID IN (2,80,60);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 90 WHERE TYRE_MANUFACTURER_ID IN (81);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 91 WHERE TYRE_MANUFACTURER_ID IN (76,64,58);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 92 WHERE TYRE_MANUFACTURER_ID IN (65);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 93 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 94 WHERE TYRE_MANUFACTURER_ID IN (67);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 95 WHERE TYRE_MANUFACTURER_ID IN (68);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 96 WHERE TYRE_MANUFACTURER_ID IN (1);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 97 WHERE TYRE_MANUFACTURER_ID IN (51,69);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 98 WHERE TYRE_MANUFACTURER_ID IN (73,63,57);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 99 WHERE TYRE_MANUFACTURER_ID IN (59,70,84);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 100 WHERE TYRE_MANUFACTURER_ID IN (75);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 101 WHERE TYRE_MANUFACTURER_ID IN (83);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 102 WHERE TYRE_MANUFACTURER_ID IN (6,53);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 103 WHERE TYRE_MANUFACTURER_ID IN (78);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 104 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE InventoryTyre SET TYRE_MANUFACTURER_ID = 105 WHERE TYRE_MANUFACTURER_ID IN (52);
    
	#UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 87 WHERE TYRE_MANUFACTURER_ID IN (87,77,66,61,55,5);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 88 WHERE TYRE_MANUFACTURER_ID IN (71,54,62); 
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 89 WHERE TYRE_MANUFACTURER_ID IN (2,80,60);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 90 WHERE TYRE_MANUFACTURER_ID IN (81);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 91 WHERE TYRE_MANUFACTURER_ID IN (76,64,58);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 92 WHERE TYRE_MANUFACTURER_ID IN (65);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 93 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 94 WHERE TYRE_MANUFACTURER_ID IN (67);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 95 WHERE TYRE_MANUFACTURER_ID IN (68);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 96 WHERE TYRE_MANUFACTURER_ID IN (1);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 97 WHERE TYRE_MANUFACTURER_ID IN (51,69);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 98 WHERE TYRE_MANUFACTURER_ID IN (73,63,57);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 99 WHERE TYRE_MANUFACTURER_ID IN (59,70,84);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 100 WHERE TYRE_MANUFACTURER_ID IN (75);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 101 WHERE TYRE_MANUFACTURER_ID IN (83);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 102 WHERE TYRE_MANUFACTURER_ID IN (6,53);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 103 WHERE TYRE_MANUFACTURER_ID IN (78);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 104 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE InventoryTyreAmount SET TYRE_MANUFACTURER_ID = 105 WHERE TYRE_MANUFACTURER_ID IN (52);
    
	#UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 87 WHERE TYRE_MANUFACTURER_ID IN (87,77,66,61,55,5);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 88 WHERE TYRE_MANUFACTURER_ID IN (71,54,62); 
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 89 WHERE TYRE_MANUFACTURER_ID IN (2,80,60);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 90 WHERE TYRE_MANUFACTURER_ID IN (81);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 91 WHERE TYRE_MANUFACTURER_ID IN (76,64,58);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 92 WHERE TYRE_MANUFACTURER_ID IN (65);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 93 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 94 WHERE TYRE_MANUFACTURER_ID IN (67);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 95 WHERE TYRE_MANUFACTURER_ID IN (68);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 96 WHERE TYRE_MANUFACTURER_ID IN (1);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 97 WHERE TYRE_MANUFACTURER_ID IN (51,69);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 98 WHERE TYRE_MANUFACTURER_ID IN (73,63,57);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 99 WHERE TYRE_MANUFACTURER_ID IN (59,70,84);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 100 WHERE TYRE_MANUFACTURER_ID IN (75);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 101 WHERE TYRE_MANUFACTURER_ID IN (83);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 102 WHERE TYRE_MANUFACTURER_ID IN (6,53);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 103 WHERE TYRE_MANUFACTURER_ID IN (78);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 104 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE purchaseorderstodebitnote SET TYRE_MANUFACTURER_ID = 105 WHERE TYRE_MANUFACTURER_ID IN (52);


    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 87 WHERE TYRE_MANUFACTURER_ID IN (87,77,66,61,55,5);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 88 WHERE TYRE_MANUFACTURER_ID IN (71,54,62); 
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 89 WHERE TYRE_MANUFACTURER_ID IN (2,80,60);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 90 WHERE TYRE_MANUFACTURER_ID IN (81);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 91 WHERE TYRE_MANUFACTURER_ID IN (76,64,58);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 92 WHERE TYRE_MANUFACTURER_ID IN (65);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 93 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 94 WHERE TYRE_MANUFACTURER_ID IN (67);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 95 WHERE TYRE_MANUFACTURER_ID IN (68);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 96 WHERE TYRE_MANUFACTURER_ID IN (1);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 97 WHERE TYRE_MANUFACTURER_ID IN (51,69);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 98 WHERE TYRE_MANUFACTURER_ID IN (73,63,57);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 99 WHERE TYRE_MANUFACTURER_ID IN (59,70,84);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 100 WHERE TYRE_MANUFACTURER_ID IN (75);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 101 WHERE TYRE_MANUFACTURER_ID IN (83);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 102 WHERE TYRE_MANUFACTURER_ID IN (6,53);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 103 WHERE TYRE_MANUFACTURER_ID IN (78);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 104 WHERE TYRE_MANUFACTURER_ID IN (74);
    #UPDATE PurchaseOrdersToParts SET TYRE_MANUFACTURER_ID = 105 WHERE TYRE_MANUFACTURER_ID IN (52);