{
showPartManufacturerTypeCol	  : false,
showBatteryPartNumber		  : true,
showRefreshmentOption         : true,
showExtendedPartSave          : false,
showPartType				  : true,
showPartNameLocal			  : false,
showPartNameBill			  : false,
showOriginalBrand			  : false,
showPartSubCategory			  : false,
showVehicleMake			  	  : false,
showVehicleModel			  : false,
showWarranty			  	  : false,
showCoupon			  		  : false,
showScrap			  		  : false,
showMainPacking			  	  : false,
showUOMMainPacking			  : false,
showLooseItem			  	  : false,
showLooseUOM			  	  : false,
showBarCodeNumber			  : false,
showItemType			      : false,
showDimention			  	  : false,
showPurchaseVendor			  : false,
showReparing			  	  : false,
showChildParts			  	  : false,
showSubstitute			  	  : false,
showDescription				  : true,
validateLocalParts			  : false,
validateWarranty			  : false,
validateDescription				: false,
validateRepairable				: false,
validatePurchaseVendor			: false,
UOMTitle                        : "Measurement Unit",
showPartLocationOption         : false,
showPartTypeCategory           : false,
showAssetIdRequired            : false,
manufacturerTitle              : "Manufacturer"
}