name: fleetop
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  json_annotation: ^2.4.0
  rflutter_alert: ^1.0.2
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.15.0
  shared_preferences: ^0.5.3+5
  device_info: ^0.4.2+1
  bottom_navy_bar: ^5.2.0
  flutter_spinkit: "^2.1.0"
  datetime_picker_formfield: ^0.4.3
  material_switch: ^0.0.5
  flutter_typeahead: ^1.7.0
  image_picker: ^0.6.1+4
  flutter_image_compress: ^0.6.3
  get_ip: ^0.4.0
  data_connection_checker: ^0.3.4
  url_launcher: ^5.0.3
  shimmer:
  location: ^2.3.5
  flutter_svg: ^0.19.0
  charts_flutter: ^0.8.1
  flutter_money_formatter: ^0.8.3
  kf_drawer: ^0.0.2
  fluttertoast: ^3.1.0
  getflutter: ^1.1.3
  esys_flutter_share: ^1.0.2
  pdf_flutter: ^1.1.3
  file_picker: "^1.12.0"
  gradient_app_bar: ^0.1.3
  path_provider: ^1.6.24
  open_file: ^3.0.3
  date_format: ^1.0.9
  nice_button: ^0.1.7
  google_nav_bar: ^4.0.2
  flip_box_bar: ^0.9.2
  google_fonts: ^0.2.0
  awesome_dialog: ^1.3.2
  button3d: ^0.1.1
  flutter_local_notifications: ^1.4.1
  firebase_messaging: ^6.0.13
  flutter_slidable: ^0.5.6
  dependencies:

  #bottom_navy_bar: ^5.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:



flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/images/
    - assets/svgs/forceupdate.svg
    - assets/images/top_header.png
    - assets/sounds/notificationSound.mp3
fonts:
  - family: WorkSans
    fonts:
      - asset: assets/fonts/WorkSans-Regular.ttf
      - asset: assets/fonts/WorkSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/WorkSans-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/WorkSans-Bold.ttf
        weight: 700
  - family: Roboto
    fonts:
      - asset: assets/fonts/Roboto-Bold.ttf
      - asset: assets/fonts/Roboto-Regular.ttf
      - asset: assets/fonts/Roboto-Medium.ttf
        weight: 400
  - family: Montserrat Regular    
    fonts:
     - asset: assets/fonts/mo_re.ttf
  - family: Montserrat Medium    
    fonts:
     - asset: assets/fonts/mo_me.ttf

