{ 
  allowGPSIntegration             : false,
  gpsUserId                       : sainitravel,
  sainiTravelsAuthorizationToken  : "noToken",
  # 1 = manual,  2 = only gps , 3 = both
  gpsFlavor                       : 1,
  smtcUsername                    : "NA",
  smtcpassword                    : "NA",
  smtcHashUrl                     : "NA",
  smtcTrackerUrl                  : "NA",
  smtcDataUrl                     : "NA",
  itsGatewayGpsUsageUrl           : "",   
  itsGatewayVerifyCall            : "hQ3A55qg553Y7V24e4e72zT8Aw39f2436kf45rv584524e37hMFT",
  multipleAccountForSameVendor    : false,
  trackNowAuthorization    : "NA",
  trackNowUrl : "NA",   
  gpsUrl : "https://api.fleetx.io/api/v1/trips/distance/day-wise",  
  gpsToken : "",  
 intangleFuelPreURL : "https://indium-apis.intangles.io/api/v1/fuel/",
  intangleFuelPostURL : "?types=filling,pilfrage&pnum=1&psize=5000",
  intangleFuelAPI_AsscessToken : "7d7713646d57a75e2f76a7cfdbdb8fa5",
  intangleAccountingURL : "https://indium-apis.intangles.io/api/v1/account/list?pnum=1&psize=5000",
  intangleTripMileageURL : "https://indium-apis.intangles.io/api/v1/trip/mileage/",
  intangleVehicleListURL : "https://indium-apis.intangles.io/api/v1/vehicle/list?pnum=1&psize=5000",
  tataAPILink : " ",
  tataAPISingleDateLink : " ",
   fleetexURL : "https://api.fleetx.io/api/v1/trips/distance/bulk?",
  fleetexCookie : "",
  eicherURL : "https://partnerapi.vecv.net/tracking/vehicletracking",
  X-IBM-Client-Id : "",
  X-IBM-Client-Secret : "",
  noOfDays        : 0
}
