{ 
vehicleHaltOnDriverHalt       : false,
flavorWiseDriverSalary        : false,
showBloodGroup                : true,
showLanguage                  : true,
showHomePhoneNumber           : true,
showAddress2                  : true,
showInsuranceNumber           : true,
showOtherTrainning            : true,   
showLeaveDate                 : true,   
showBadgeNo                   : true,   
showLicenseClass              : true,
showLicenseState              : true,   
showAuthorizedToDrive         : true,   
showOriginalDLRemark          : true,   
showReferenceData             : true,
showDateOfBirth               : true,
showEmployeeNumber            : true,
showStartDate                 : true,
showAadharNumber              : true,
showCheckingEntryDetails      : false,
showRenewalType            : false,
showRenewalValidity        : false,
showDueThreshold           : false,
showRenewalDoc             : false,
showVehicle                : false,
showDriverEmail            : true,
showESINumber              : true,
showPFNumber               : true,
showQualification          : true,
showBankAccount            : true,
showIFSCCode               : true,
showBankName               : true,
addDriverDetailsAjax       : true,
validateDateOfBirth        : true,
validateGroup              : true,
validateSalaryType         : true,
validatePerDaySalary       : false,
validateMobileNo           : true,
validateEmployeeNumber     : true,
validateInsuranceNumber    : false,
validateStartDate          : true,
validateJobTitle           : true,
validateDLNumber           : true,
allowDLNumber              : true,
validateRenwalType         : false,
validateRenewalPeriod      : false,
validateRenewalThreshold   : false,
validateRenwalDoc          : false,
validateAadhar             : true,
validateVehicle            : false,
showPanNo                  : true,
showSalariedEmp            : false,
editInActiveDriver         : false,
autoGenerateEmpNo          : false,
jobTypeWiseAutoGenerateEmpNo  : false,
validateDLNumberWhenJobTypeIsDriver           : true,
firstDriverExpenseId       : 0,
secondDriverExpenseId      : 0,
cleanerExpenseId           : 0,
driverRenewalReceipt       : false,
addStatusChangeRemark : false,
IncTripExpenseInDriverSalary 		: false,
 silverTripSlabForSingleTrip  : 0,
 silverTripSlabForRoundTrip   : 0,
 goldenTripSlabForSingleTrip  : 0,
 goldenTripSlabForRoundTrip   : 0,
 goldenSlabTripCount          : 0

}