{showVehicleServiceEntriesBreakDown			   : true,
showVehicleWorkOrdersBreakDown			       : true,
showVehicleIssuesBreakDown			           : true,
showVehicleCommentsBreakDown	               : true,
showVehicleTripSheetsBreakDown		           : true}