{
  showUserInVehicleRepairReport                 : false,
  showVehicleFilter                             : false,
  hideSomeVehicleReportOptions	  				: false,
  showVehicleNo					   				: false 
 }
