{
showOutWorkStationCol			   : false,
showDriverNumberCol                : false,
showRouteCol                       : false,
AddNewWorkLocation                 : false,
autoCapitalAllTestFeilds           : false,
showStartAndDueTimeField           : false,
showCompanyWisePrint               : false,
showJobTypeRemarkCol               : false,
showDieselCol                      : false,
showEditJobTypeRemark              : false,
showPONoFeild                      : false,
companyWisePrintOnClosedStatus     : false,
showServRemindWhileCreatingWO      : true,
partsCreatedBy					   : false,
workshopInvoiceAmount              : false,
validateInvNumForServEnt           : true,
validateInvDateForServEnt          : true,
validatePaidDateForServEnt         : false,
showAddInvoiceDeatils              : false,
TallyCompanyMasterInWO             : false,
noOfDaysForWorkOrderBackDate       : 15,
noOfDaysToReOpenWorkOrder          : 15,
allowToCreateWOInTripRouteStatus   : false,
showSubLocation                     : false,  
mainLocationIds                     : "", 
showMakeApproval                   : false,
invoiceWisePartList                   : false,
multipleApproval                   : false,
autoLabourAdd                       : false,
workOrderTaskToPartDocument         : false,
showPendingIssueWhileCreatingWO      : false,
removeFeildFromLaborTab		         : false,
showVehicleHealthStatus		         : false,
addWOCompletionRemark                : false,
validatePaidDateForServEntOnCash     : true,
showServiceProgramINWO               : false,
serviceReminderLebel                 : "Service Reminder",
removeTaskAtCreation                 : false,
showCurrentDateAtWOStartDate         : false,
populateEndDateOnIssue               : false,
addHoldRemark						 : false,
addInprocessRemark					 : false,
storeLocation                        : false,
workLocation                         : false,
showDocumentColumn                   : true ,
showIssueSummaryInList               : false ,
showTaskInList                       : false ,
showAllTaskCompleteOption            : false ,
showIssueInWO                        : false ,
multiIssueInWO                     : false,
taskForIssueMandatory              : false ,
remarkForIssueMandatory            : false ,
showSubstitutePartsInList          : false,      

tyreAssginFromWO                   : false,  
tyreAssignmentJobType              : 0,                 
tyreAssignmentSubJobType           : 0,
multipleQuotation                  : false,
validatIssueDetailsOrServiceProgramm : false,
driverSignatureInWorkOrderPrint		 : false,
HideAmountInWorkOrderPrint       	 : false,
showPartCategoriesDropdown			 : false,
showPartCategoriesList               : false,
allowReasonRepairType                : true,
getPerDayWorkingHourForDriver        : 0,
showLabourTotalCost                  : true,
showLaborDataInWO                    : false
}