{
 vehicleTyreSizeMasterCommon     : true,
 isCommonTyreModel               : true,
 commonPartCategory              : true,
 commonManufacturer              : true,
 commonMasterParts               : true,
 showRotInServiceReminder        : false,
 tripIncomeWithRate              : false,
 showROTCode                     : false,
 showNoOfHour                    : false,
 showROTAmount                   : false,
 vehicleModelTyreLayout          : false,
 tyreModalTypeId                 : false, 
 gauageMeasurementLine           : false,
 tyreGauge                       : false,
 tyreTubeTypeId                  : false, 
 tyrePly                         : false, 
 tyrePsi                         : false,
 tyreModelSizeId                 : false,
 validateTyreSize                : true,
 validateTyreManufactuer         : true,
 validateTyreModel               : true,
 validateVehicleModel            : true,
 inIssueCategory				 : false
}